# https://medium.com/estia-training/the-journey-to-building-a-full-microservice-app-docker-compose-and-connection-with-mongodb-cd6cdd26b11c
# https://docs.docker.com/compose/compose-file/
# docker-compose up --build -d
# docker-compose up --build -d --force-recreate --renew-anon-volumes # If mongo password changes
# docker-compose down

version: "3.7"

services:
  mongo-database:
    image: mongo:3
    container_name: authentication-mongo-database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    # volumes:
    #   - "./.db:/data/db"      # Not working on MacOS
    networks:
      - authentication-service

  server:
    container_name: authentication-server
    image: authentication-server
    working_dir: /source
    command: yarn run dev
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "./:/source"
    environment:
      BABEL_DISABLE_CACHE: "${BABEL_DISABLE_CACHE}"
      NODE_ENV: "${NODE_ENV}"
      PORT: "${PORT}"
      HOST: "${HOST}"
      MONGO_SERVER: "mongo-database"
      MONGO_PORT: "${MONGO_PORT}"
      MONGO_DATABASE: "${MONGO_DATABASE}"
      MONGO_USERNAME: "${MONGO_USERNAME}"
      MONGO_PASSWORD: "${MONGO_PASSWORD}"
    depends_on:
      - mongo-database
    networks:
      - authentication-service
  # https://medium.com/@renato.groffe/mongodb-mongo-express-docker-compose-montando-rapidamente-um-ambiente-para-uso-824f25ca6957
  # Securing mongo-express: https://www.helpnetsecurity.com/2019/04/26/securing-mongo-express-web-administrative-interfaces/
  mongo-express:
    image: mongo-express
    container_name: authentication-mongo-express
    ports:
      - "8090:8090"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-database
      # - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      VCAP_APP_PORT: 8090
      ME_CONFIG_OPTIONS_EDITORTHEME: cobalt
    depends_on:
      - mongo-database
    networks:
      - authentication-service

networks:
  authentication-service:
    name: authentication-service
    driver: bridge
